---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: easytrade
    kubernetes.io/ingress.class: public
  labels:
    app: easytrade
  name: easytrade
spec:
  rules:
  - host: easytrade.INGRESS_DOMAIN
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontendreverseproxy-easytrade
                port:
                  number: 80