---
#############
# k3s Tasks #
#############
- name: Install k3s
  become: true
  shell:
    cmd: 'curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - --disable servicelb --write-kubeconfig-mode=644 --egress-selector-mode=disabled'

- name: Add KUBECONFIG to user .bashrc
  lineinfile:
    path: "/home/{{ instance_user }}/.bashrc"
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
    create: yes
    owner: "{{ instance_user }}"
    group: "{{ instance_user }}"
    mode: "0644"

################
# Docker Tasks #
################

- name: Ensure Docker prerequisites
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Ensure keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key (ASC format)
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Detect architecture
  become: true
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false


- name: Add Docker APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present


- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present


- name: Enable Docker service
  become: true
  systemd:
    name: docker
    enabled: yes

#################
# Restart Tasks #
#################

- name: Restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart k3s
  become: true
  ansible.builtin.service:
    name: k3s
    state: restarted
