- include_vars: "{{ aether_config_file_path }}"

- name: Include task files
  include_tasks: "{{ item }}"
  loop:
    - kubernetes.yml
    - dynatrace-operator.yml
    - app-easytrade.yml
    - app-otel-demo.yml
